//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationEF.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartado()
        {
            this.Leccion = new HashSet<Leccion>();
        }
    
        public int NumApartado { get; set; }
        public int NumCalendario { get; set; }
        public string CodDocente { get; set; }
        public string CodGrupo { get; set; }
        public int Bloque { get; set; }
        public string TipoBloque { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Calendario Calendario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leccion> Leccion { get; set; }
    }
}
