//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationEF.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blacklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blacklist()
        {
            this.DetalleBlacklist = new HashSet<DetalleBlacklist>();
        }
    
        public int NumBlacklist { get; set; }
        public string CodResponsable { get; set; }
        public string Causa { get; set; }
        public System.DateTime Sanción { get; set; }
        public int Bloque { get; set; }
        public bool Vigente { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
    
        public virtual Responsable Responsable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleBlacklist> DetalleBlacklist { get; set; }
    }
}
