//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationEF.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleBlacklist
    {
        public int IdDetalleBlacklist { get; set; }
        public int NumBlacklist { get; set; }
        public string CodGrupo { get; set; }
        public string CodTurno { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    
        public virtual Blacklist Blacklist { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
