//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationEF.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleExamen
    {
        public int IdDetalleExamen { get; set; }
        public int NumExamen { get; set; }
        public int NumMaquina { get; set; }
        public string Estado { get; set; }
        public string Desperfecto { get; set; }
    
        public virtual Examen Examen { get; set; }
        public virtual Maquina Maquina { get; set; }
    }
}
