//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationEF.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leccion
    {
        public int NumLeccion { get; set; }
        public int NumApartado { get; set; }
        public string CodAsignatura { get; set; }
        public Nullable<int> CantHombre { get; set; }
        public Nullable<int> CantMujer { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
    
        public virtual Apartado Apartado { get; set; }
        public virtual Asignatura Asignatura { get; set; }
    }
}
