//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationEF.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_blacklist
    {
        public int ID { get; set; }
        public string Responsable { get; set; }
        public string Causa { get; set; }
        public System.DateTime Sanción { get; set; }
        public int Bloque { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    }
}
