//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationEF.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_leccion
    {
        public int ID { get; set; }
        public int Apartado { get; set; }
        public string Asignatura { get; set; }
        public Nullable<int> Varones { get; set; }
        public Nullable<int> Mujeres { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    }
}
