//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationEF.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_maquina
    {
        public int ID { get; set; }
        public string Fábrica { get; set; }
        public string Módelo { get; set; }
        public string CPU { get; set; }
        public int RAM { get; set; }
        public string GPU { get; set; }
        public int HDD { get; set; }
    }
}
