//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationEF.Diagrama
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_detalleexamen
    {
        public int ID { get; set; }
        public int Examen { get; set; }
        public int Nº_Máquina { get; set; }
        public string Estado { get; set; }
        public string Desperfecto { get; set; }
    }
}
